website/home/urls.py
from django.urls import path
from . import views

app_name="home"

urlpatterns = [
    path('', views.home, name='home'),
    path('gallery/', views.gallery, name='gallery'),
    path('events/', views.events, name='events'),
    path('events/detail/<slug:slug>/', views.event_detail, name='event-detail'),
    path('contact-us/', views.contact, name='contact'),
    path('committee/', views.team, name='team'),
    path('executive-council/', views.executiveCouncil, name='executive-council'),

    # About Us
    path('about-iste/', views.about_iste, name='about-iste'),
    path('code-of-conduct/', views.code_of_conduct, name='code-of-conduct'),
    path('objective/', views.objective, name='objective'),
    path('about-section/', views.about_section, name='about-section'),
    path('section-student-chapters/', views.student_chapters, name='student-chapters'),
    path('section-faculty-chapters/', views.faculty_chapters, name='faculty-chapters'),

    # Join ISTE
    path('establish-chapter/', views.establish_chapter, name='establish-chapter'),
    path('establish-student-chapter/', views.establish_student_chapter, name='establish-student-chapter'),
    path('incentive-chapter/', views.incentive_chapter, name='incentive-chapter'),
    path('incentive-student-chapter/', views.incentive_student_chapter, name='incentive-student-chapter'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/home/models.py
from email.policy import default
from enum import unique
from django.db import models
from django.utils import timezone
from .utils import unique_slug_generator

class Gallery(models.Model):
  title = models.CharField(max_length=100)
  image=models.ImageField(upload_to='images/gallery')
  date = models.DateField(default=timezone.localdate)

  created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
  
  def __str__(self):
         return self.title

class carousel(models.Model):
  title = models.CharField(max_length=100)
  image=models.ImageField(upload_to='images/gallery')
  date = models.DateField(default=timezone.localdate)

  created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
  
  def __str__(self):
         return self.title
class Event(models.Model):
  title = models.CharField(max_length=100)
  date = models.DateTimeField(default=timezone.now)
  venue = models.CharField(max_length=100, default='Online')
  description = models.TextField(max_length=5000,blank=True)
  image=models.ImageField(upload_to='events/', null=True, blank=True)
  slug = models.SlugField(max_length = 250, null = True, blank = True, unique=True)
  
  title_link1 = models.CharField(max_length=200, default='', blank=True)
  url_link1 = models.URLField(blank=True)
  title_link2 = models.CharField(max_length=200, default='', blank=True)
  url_link2 = models.URLField(blank=True)
  title_link3 = models.CharField(max_length=200, default='', blank=True)
  url_link3 = models.URLField(blank=True)
  
  title_file1 = models.CharField(max_length=200, default='', blank=True)
  upload_file1 = models.FileField(upload_to='events/',null = True , blank=True)
  title_file2 = models.CharField(max_length=200, default='', blank=True)
  upload_file2 = models.FileField(upload_to='events/',null = True , blank=True)
  title_file3 = models.CharField(max_length=200, default='', blank=True)
  upload_file3 = models.FileField(upload_to='events/',null = True , blank=True)

  created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
  
  def __str__(self):
         return self.title

  def save(self, *args, **kwargs):  # new
        if not self.slug:
            self.slug = unique_slug_generator(self)
        return super().save(*args, **kwargs)

class Announcement(models.Model):
  title = models.CharField(max_length=100)
  file = models.FileField(upload_to='announcement/file/',null = True , blank=True)
  date = models.DateField(default=timezone.localdate)

  created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
  
  def __str__(self):
         return self.title

class Contact(models.Model):
  name = models.CharField(max_length=100)
  phone1 = models.IntegerField(default=9999999999)
  phone2 = models.IntegerField(default=9999999999)
  email = models.EmailField()
  location = models.TextField(max_length=5000,blank=True)

  created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
  
  def __str__(self):
         return self.name

class Post(models.Model):
  title = models.CharField(max_length=100) 
  priority = models.IntegerField(default=0)
  
  def __str__(self):
         return self.title + " (Priority - " + str(self.priority) + ")"

class PostBearer(models.Model):
  name = models.CharField(max_length=100)
  post = models.ForeignKey('Post', null=True, on_delete=models.CASCADE)
  image = models.ImageField(upload_to='images/PostBearer',null = True)
  introduction = models.TextField(max_length=200,default=" ", blank=True, null=True)
  description = models.TextField(max_length=5000,default=" ", blank=True, null=True)
  link = models.URLField(null=True, blank=True, default='')

  created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)
  
  def __str__(self):
         return "P " + str(self.post.priority) + " - " + str(self.post.title) + " - " + self.name

class StudentChapter(models.Model):
  name = models.CharField(max_length=100)
  chapter_code = models.CharField(max_length=100)
  college = models.CharField(max_length=100)
  address = models.TextField(max_length=500)
  email = models.EmailField()

  def __str__(self):
    return str(self.chapter_code) + " - " + str(self.name)

class FacultyChapter(models.Model):
  name = models.CharField(max_length=100)
  chapter_code = models.CharField(max_length=100)
  college = models.CharField(max_length=100)
  address = models.TextField(max_length=500)
  email = models.EmailField()

  def __str__(self):
    return str(self.chapter_code) + " - " + str(self.name)

website/home/views.py
from django.shortcuts import render
from . import models
from datetime import datetime
from django.urls import reverse_lazy

def home(request):
    today = datetime.now()
    chairman = models.PostBearer.objects.all().filter(post__priority=1).first()
    secretary = models.PostBearer.objects.all().filter(post__priority=2).first()
    carousel_data = models.carousel.objects.all().order_by('-date')
    announcements = models.Announcement.objects.all().order_by('-date')[:5]
    upcoming_events = models.Event.objects.all().filter(date__gte=today).order_by('-date')[:5]
    past_events = models.Event.objects.all().filter(date__lt=today).order_by('-date')[:(5-len(upcoming_events))]
    context = {
        'announcements': announcements, 
        'chairman':chairman, 
        'secretary':secretary, 
        'c_data': carousel_data, 
        'upcoming_events':upcoming_events,
        'past_events':past_events
    }
    return render(request, 'home.html',context)

def about_iste(request):
    return render(request, 'iste/about_iste.html',{})

def about_section(request):
    return render(request, 'section/about_section.html',{})

def code_of_conduct(request):
    return render(request, 'iste/code_of_conduct.html',{})

def objective(request):
    return render(request, 'iste/objective.html',{})

def student_chapters(request):
    chapters = models.StudentChapter.objects.all()
    return render(request, 'section/student_chapters.html',{'chapters':chapters})

def faculty_chapters(request):
    chapters = models.FacultyChapter.objects.all()
    return render(request, 'section/faculty_chapters.html',{'chapters':chapters})

def gallery(request):
    images = models.Gallery.objects.all().order_by('-date')
    return render(request, 'gallery.html',{'images': images}) 

def events(request):
    today = datetime.now()
    upcoming_events = models.Event.objects.all().filter(date__gte=today).order_by('-date')
    past_events = models.Event.objects.all().filter(date__lt=today).order_by('-date')
    return render(request, 'events.html',{'upcoming_events': upcoming_events, 'past_events':past_events})

def event_detail(request, slug):
    q = models.Event.objects.filter(slug__iexact = slug)
    if q.exists():
        q = q.first()
    else:
        return reverse_lazy('events')
    return render(request, 'event_details.html', {'event': q})

def team(request):
    members = models.PostBearer.objects.all().order_by('post__priority')
    return render(request, 'team.html',{'members':members})

def executiveCouncil(request):
    members = models.PostBearer.objects.all().order_by('post__priority')
    return render(request, 'executive_council.html',{'members':members})

def contact(request):
    contact = models.Contact.objects.all().first()
    return render(request, 'contact-us.html',{'contact':contact})

def establish_chapter(request):
    return render(request, 'join_iste/establish_chapter.html',{})

def incentive_chapter(request):
    return render(request, 'join_iste/incentive_chapter.html',{})

def establish_student_chapter(request):
    return render(request, 'join_iste/establish_student_chapter.html',{})

def incentive_student_chapter(request):
    return render(request, 'join_iste/incentive_student_chapter.html',{})

website/home/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalab=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Package Imports-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Import Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Font Imports -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400;1,700&display=swap"
        rel="stylesheet">

    <!--File Imports-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base_css.css' %}">
    <link rel="stylesheet" href="{% static 'css/home_css.css' %}">
    <link rel="stylesheet" href="{% static 'css/loader_css.css' %}">
    <!-- galley css -->
    <link rel="stylesheet" href="{% static 'css/gallery_css.css' %}">
    <link rel="stylesheet" href="https://rawgit.com/LeshikJanz/libraries/master/Bootstrap/baguetteBox.min.css">

    <!-- Favicon import -->
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'image/favicon.ico' %}">

    {% block css %} {% endblock %}
    {% block js %} {% endblock js %}

    <title>
        {% block title %} {% endblock %}
    </title>

</head>

<body onload="loaderfunction()">
    <div id="loader">
        <div id="loading">
            <div class="loading-screen">
                <div class="loading-animation">
                    <img src="{% static 'image/Loader.png' %}" alt="" class="logo">
                    <div class="loading-bar"></div>
                </div>
            </div>
        </div>
    </div>

    <nav class="navbar sticky-top navbar-expand-sm navbar-dark " style="background-color: #111a2d; margin-bottom: 0%; ">
        <div class="container">
            <div class="container">
                <a class="navbar-brand text-responsive p-1" href="{% url 'home:home' %}">
                    {% load static %}
                    <img id="logoISTE" src="{% static 'image/logo.png'%}" style="max-width:50px;" alt="logo">
                    <strong>ISTE</strong> West Bengal Section
                </a>
                <button class="navbar-toggler p-1 float-end" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav" style="white-space:nowrap; text-align: center;">

                    {% if request.path == "/" %}
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link m-2 {% block home_active %}{% endblock %}"
                            href="{% url 'home:home' %}">Home</a>
                    </li>
                    {% endif %}


                    <li class="nav-item">
                        <a class="nav-link m-2" href="http://www.isteonline.in">ISTE</a>
                    </li>
                    <li class="nav-item dropdown m-2">
                        <a class="nav-link dropdown-toggle tab {% block about-iste %}{% endblock %}" href="#"
                            role="button" data-bs-toggle="dropdown">About Us</a>
                        <ul class="dropdown-menu ml-2"
                            style="padding: 2px; background-color: #111a2d; text-align: center;">
                            <li><a class="dropdown-item" href="{% url 'home:about-iste' %}">About ISTE</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:about-section' %}">About WB Section</a></li>
                            <!-- <li><a class="dropdown-item" href="{% url 'home:code-of-conduct' %}">Code of Conduct</a>
                            </li> -->
                            <li><a class="dropdown-item" href="{% url 'home:objective' %}">Objective & Overview</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:student-chapters' %}">Student Chapters</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:faculty-chapters' %}">Faculty Chapters</a></li>
                            <!-- <li><a class="dropdown-item" href="https://membership.isteonline.in/" target="_blank">Online
                                    Membership</a></li> -->
                        </ul>
                    </li>
                    <li class="nav-item dropdown m-2">
                        <a class="nav-link dropdown-toggle tab {% block join-iste %}{% endblock %}" href="#"
                            role="button" data-bs-toggle="dropdown">Join ISTE</a>
                        <ul class="dropdown-menu ml-2"
                            style="padding: 2px; background-color: #111a2d; text-align: center;">
                            <li><a class="dropdown-item" href="{% url 'home:establish-chapter' %}">How to Establish an
                                    ISTE Chapter</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:establish-student-chapter' %}">How to
                                    Establish an ISTE Students Chapter</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:incentive-chapter' %}">Incentives to ISTE
                                    Chapter</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:incentive-student-chapter' %}">Incentives to
                                    ISTE Students Chapter</a></li>
                            <li><a class="dropdown-item" href="https://membership.isteonline.in/" target="_blank">Online
                                    Membership</a></li>
                        </ul>
                    </li>
                    <!-- <li class="nav-item dropdown m-2">
                    <a class="nav-link dropdown-toggle tab" href="#" role="button" data-bs-toggle="dropdown">Dropdown</a>
                    <ul class="dropdown-menu ml-2" style="padding: 2px; background-color: #111a2d;">
                      <li><a class="dropdown-item" href="#">Link</a></li>
                      <li><a class="dropdown-item" href="#">Another link</a></li>
                      <li><a class="dropdown-item" href="#">A third link</a></li>
                    </ul>
                </li> -->
                    <li class="nav-item">
                        <a class="nav-link m-2 {% block events %}{% endblock %}"
                            href="{% url 'home:events' %}">Events</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link m-2 {% block gallery %}{% endblock %} "
                            href="{% url 'home:gallery' %}">Gallery</a>
                    </li>
                    <li class="nav-item dropdown m-2">
                        <a class="nav-link dropdown-toggle tab {% block team %}{% endblock %}" href="#"
                            role="button" data-bs-toggle="dropdown">Committee</a>
                        <ul class="dropdown-menu ml-2"
                            style="padding: 2px; background-color: #111a2d; text-align: center;">
                            <li><a class="dropdown-item" href="{% url 'home:team' %}">Section Managing Committee</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:executive-council' %}">Executive Council Member</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link m-2 {% block contact %}{% endblock %}"
                            href="{% url 'home:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock %}


    <footer class="section footer-classic context-dark" style="background-color: #111a2d;">
        <div class="container">
            <br>
            <div class="row">
                <div class="col-md-4 col-xl-4" style="text-align: center;">
                    <h4 style="color: white;">Indian Society for Technical Education</h4>
                    <img id="logoISTE" src="{% static 'image/logo.png'%}"
                        style="max-width:50px; padding-bottom: 4px; margin-left: 5px;" alt="logo">
                    <h4 style="color: white;">West Bengal Section</h4>
                </div>
                <div class="col-md-5 col-xl-5" style="text-align: center;">
                    <h3 style="color: white;">Contact Us</h3>
                    <p style="color: white;">ISTE West Bengal Section<br>
                        C/o. FOSET, 15N, Nelli Sengupta Sarani,<br>
                        New CMC Building (5th Floor), <br> Kolkata, West Bengal 700087.<br>
                        Email: <a href="mailto:iste.wbsection@gmail.com">iste.wbsection@gmail.com</a></p>
                </div>
                <div class="col-md-3 col-xl-3" style="text-align: center;">
                    <h3 style="color: white;">Useful Links</h3>
                    <ul style="color: white;list-style-type:none;">
                        <li><a style="text-decoration:none ; color: white;" href="http://www.isteonline.in">ISTE</a></li>
                        <li><a style="text-decoration:none ; color: white;" href="{% url 'home:about-iste' %}">About ISTE</a></li>
                        <li><a style="text-decoration:none ; color: white;" href="{% url 'home:gallery'%}">Gallery</a></li>
                        <li><a style="text-decoration:none ; color: white;" href="{% url 'home:home'%}">Events</a></li>
                        <li><a style="text-decoration:none ; color: white;" href="https://membership.isteonline.in/">Online
                                Membership</a></li>
                    </ul>
                </div>
                <hr style="color: white;">
                <div style="text-align:center; color: white;">
                    <!-- Credits -->
                    Developed & Maintained by
                    <strong style="color: white;"><a style="text-decoration:none ;"
                            href="https://www.istenitdgp.com/" target="_blank">ISTE Students Chapter NIT
                            Durgapur</a></strong>
                    <!-- | Maintained by 
                    <strong style="color: white;"><a style="text-decoration:none;"
                            href="{% url 'home:home' %}" target="_blank">ISTE WB Section</a></strong> -->

                    <!-- Rights-->
                    <p style="color: white;" class="rights"><span>©  </span>
                        <span class="copyright-year">
                            <script>document.write(new Date().getFullYear())</script>
                        </span>
                        <span>ISTE WB Section</span>
                        <span>. </span>
                        <span>All Rights Reserved.</span>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'js/loader.js' %}"></script>
</body>

</html>

website/home/templates/contact-us.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ISTE WB Section {% endblock title %}

{% block contact %}active{% endblock %}

{% block content %} {% load widget_tweaks %}

<section class="container mt-5">
    <!--Contact heading-->
    <div class="row">
        <div class="col-sm-12 text-center mb-4">
            <h1>Contact Us</h1>
        </div>
        <!--Grid column-->

        <!--Grid column-->

        <!--Grid column-->
        <!--Google map-->
        <div class="col-lg-6 col-md-12">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15228.105721792223!2d88.34726367080063!3d22.553628114643082!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a02770638be7969%3A0x5cdd4429a3dbfbc3!2sForum%20of%20Scientist%20Engineers%20%26%20Technologists%20(FOSET)!5e0!3m2!1sen!2sin!4v1665643607800!5m2!1sen!2sin"
                width="100%" height="350" style="border: 2px;" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <div class="col-lg-1 col-md-0">

        </div>
        <!--Buttons-->
        <div class="col-lg-5 col-md-12">
            <br>
            <br>
            <div class="row">
                <div class="col-lg-3 col-md-4">
                    <a class="bg-primary px-3 py-2 rounded text-white mb-2 d-inline-block"><i
                            class="fa fa-phone"></i></a>
                </div>
                <div class="col-lg-9 col-md-8">
                    <p><strong>{{contact.name}}</strong><br>{{contact.phone1}} <br> {{contact.phone2}} </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-4">
                    <a class="bg-primary px-3 py-2 rounded text-white mb-2 d-inline-block"><i
                            class="fa fa-envelope"></i></a>
                </div>
                <div class="col-lg-9 col-md-8">
                    <p>{{contact.email}}</p>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-3 col-md-4">
                    <a class="bg-primary px-3 py-2 rounded text-white mb-2 d-inline-block"><i
                            class="fa fa-map-marker"></i></a>
                </div>
                <div class="col-lg-9 col-md-8">
                    <p> {{contact.location | safe}}</p>
                </div>
            </div>
        </div>
        <!--Grid column-->
    </div>
</section>

{% endblock %}

website/home/templates/events.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ISTE WB Section {% endblock title %}

{% block events %}active{% endblock %}

{% block css %}
<style>
    .eventPageHr {
        margin-top: 24px;
        height: 2px;
        margin-left: auto;
        margin-right: auto;
    }

    @media (max-width: 476px) {
        .eventPageImage img {
            max-width: 90%;
            display: block;
            margin-left: auto;
            margin-right: auto;
            margin-bottom: 18px;
        }

        .eventPageDescription {
            padding: 0 9%;
        }

        .eventPageHr {
            width: 90%;
        }
    }
</style>
{% endblock %}

{% block content %} {% load widget_tweaks %}

<br>
<h1 style="text-align:center;">EVENTS</h1>
<br>
<div class="container">
    {% if upcoming_events or past_events %}
    {% if upcoming_events %}
    {% for event in upcoming_events %}
    <div class="row">
        <div class="col-lg-2 col-md-4 col-sm-12 eventPageImage">
            {% if event.image %}
            <img src="{{event.image.url}}" style="width: 100%;">
            {% else %}
            <img src="{% static 'image/logo.png'%}" style="width: 100%;">
            {% endif %}
        </div>
        <div class="col-lg-10 col-md-8 col-sm-12 eventPageDescription">
            <h3><a href="{% url 'home:event-detail' event.slug %}"
                    style="text-decoration:none; color: #163269;">{{event.title}}</a></h3>
            <img src="{% static 'image/tnew.gif'%}">
            <i class="fa fa-calendar"> </i> {{event.date}} | <i class="fa fa-map-marker"> </i> {{event.venue}}
            <br><br>
            {{event.description | safe | truncatechars:200}}
            <a href="{% url 'home:event-detail' event.slug %}"> Continue Reading</a>
        </div>
        <hr class="eventPageHr">
    </div>
    {% endfor %}
    {% endif %}
    {% if past_events %}
    {% for event in past_events %}
    <div class="row">
        <div class="col-lg-2 col-md-4 col-sm-12 eventPageImage">
            {% if event.image %}
            <img src="{{event.image.url}}" style="width: 100%;">
            {% else %}
            <img src="{% static 'image/logo.png'%}" style="width: 100%;">
            {% endif %}
        </div>
        <div class="col-lg-10 col-md-8 col-sm-12 eventPageDescription">
            <h3><a href="{% url 'home:event-detail' event.slug %}"
                    style="text-decoration:none; color: #163269;">{{event.title}}</a></h3>
            <i class="fa fa-calendar"> </i> {{event.date}} | <i class="fa fa-map-marker"> </i> {{event.venue}}
            <br><br>
            {{event.description | safe | truncatechars:200}}
            <a href="{% url 'home:event-detail' event.slug %}"> Continue Reading</a>
        </div>
        <hr class="eventPageHr">
    </div>
    {% endfor %}
    {% endif %}
    {% else %}
    <br>
    <p style="text-align: center;">
        Stay tuned for latest updates!!
    </p>
    {% endif %}
</div>
{% endblock %}

website/home/templates/executive_council.html
{% extends 'base.html' %}
{% load static %}
{% block title %} ISTE WB Section {% endblock title %}

{% block team %}active{% endblock %}

{% block content %} {% load widget_tweaks %}
{% block css %}
<style>
    .committee-cardbody {
        border-top-right-radius: 20px;
        border-bottom-right-radius: 20px;
    }
    @media (max-width: 765px) {
        .committee-img{
            margin-left: auto;
            margin-right: auto;
        }
        .committee-cardbody h5,
        .committee-cardbody h6 {
            text-align: center;
        }
    }
</style>
{% endblock %}

<div class="container" style="margin-top: 10px;">
    <div class="row home-title">
        <h1>ISTE WB Section Executive Council Members</h1>         
    </div>
    <div class="row">
        {% for member in members %}
        {% if member.post.title == 'Executive Council Member' %}
        <div class="col-lg-2 col-md-4 col-sm-6 committee-img" style="margin-top: 10px;">
            <img src="{{member.image.url}}" alt="{{member.name}}" style="width:100%; border: 0.5px solid black;">
        </div>
        <div class="col-lg-4 col-md-6 col-sm-12 committee-cardbody">
            <br>
            <h5>{{member.name}}</h5>
            <h6>{{member.post.title}}</h6>
            <h6>{{member.introduction | safe}}</h6>
            {% if member.link %}
            <h6><a href="{{member.link}}" target="_blank">Know More</a></h6>
            {% endif %}
        </div>
        <!-- <div class="col-lg-1 col-md-12">
        </div> -->
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}